### ISSUE TITLE
MaxK speedup not realized in PyTorch training.

### ISSUE THREAD

**Issue by chasewalker26** [harveyp123/MaxK-GNN#1]
Hi, I have followed the provided documentation on the GitHub to get all of your evaluation methods up and running. I have had zero errors running any of the code, but when I run the PyTorch training with ReLU vs with MaxK, MaxK trains slower. I have tried the Reddit and PubMed datasets as well as k values of 8, 16, and 32. 

Is there something missing in the PyTorch code to force the new MaxK cuda kernel to execute and realize the speedup as claimed in the paper?

**Comment by harveyp123** [comment]
Hi, we haven't fully release the PyTorch + CUDA kernel fusion yet, we plan to release it after we solve some potential IP issue

**Comment by chasewalker26** [comment]
Hi, when will that be? Was that not already implemented to gather the results presented in the paper?
